version: '3'

services:
  php:
    image: bitnami/php-fpm:7.3.6
    ports:
      - "9000:9000"
    volumes:
      - ./:/code
      - ./php.ini:/opt/bitnami/php/etc/conf.d/php.ini
    env_file:
      - ./src/.env
